SET APPINFO ON
SET ECHO OFF
SET SERVEROUTPUT ON
SET TIMING ON
SET VERIFY OFF
SET HEADING OFF 
SET FEEDBACK OFF
SET TERMOUT ON

ACCEPT schema_name PROMPT 'Ingrese el nombre del esquema: '

Prompt Inicia

SPOOL  log_creacion.txt

Prompt Creando Tablas del Modelo

Prompt Table E_AUDIT;
CREATE TABLE &schema_name..E_AUDIT
(
  AUDITID        NUMBER(9),
  TABLENAME      VARCHAR2(100 BYTE),
  OBJECTEXECUTE  VARCHAR2(100 BYTE),
  OPERATION      VARCHAR2(10 BYTE),
  CREATEAT       DATE,
  UPDATEAT       DATE,
  MODULE         VARCHAR2(100 BYTE),
  VALUEOLD       VARCHAR2(4000 BYTE),
  VALUENEW       VARCHAR2(4000 BYTE),
  ATRIBUTE       VARCHAR2(100 BYTE),
  GLOSSA         VARCHAR2(4000 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE;

Prompt Index E_AUDITORIA_PK;
CREATE UNIQUE INDEX &schema_name..E_AUDITORIA_PK ON &schema_name..E_AUDIT
(AUDITID)
LOGGING;

ALTER TABLE &schema_name..E_AUDIT ADD (
  CONSTRAINT E_AUDITORIA_PK
  PRIMARY KEY
  (AUDITID)
  USING INDEX &schema_name..E_AUDITORIA_PK
  ENABLE VALIDATE);


Prompt Table E_COUNTRY;
CREATE TABLE &schema_name..E_COUNTRY
(
  COUNTRYID  NUMBER(9),
  NAME       VARCHAR2(256 BYTE)                 NOT NULL
)
LOGGING 
NOCOMPRESS 
NOCACHE;


Prompt Index E_COUNTRY_PK;
CREATE UNIQUE INDEX &schema_name..E_COUNTRY_PK ON &schema_name..E_COUNTRY
(COUNTRYID)
LOGGING;

ALTER TABLE &schema_name..E_COUNTRY ADD (
  CONSTRAINT E_COUNTRY_PK
  PRIMARY KEY
  (COUNTRYID)
  USING INDEX &schema_name..E_COUNTRY_PK
  ENABLE VALIDATE);


Prompt Table E_MUNICIPALITY;
CREATE TABLE &schema_name..E_MUNICIPALITY
(
  MUNICIPALITYID  NUMBER(9)                     NOT NULL,
  NAME            VARCHAR2(256 BYTE)            NOT NULL,
  COUNTRYID       NUMBER(9)                     NOT NULL
)
LOGGING 
NOCOMPRESS 
NOCACHE;


Prompt Index E_MUNICIPALITY_PK;
CREATE UNIQUE INDEX &schema_name..E_MUNICIPALITY_PK ON &schema_name..E_MUNICIPALITY
(MUNICIPALITYID)
LOGGING;

ALTER TABLE &schema_name..E_MUNICIPALITY ADD (
  CONSTRAINT E_MUNICIPALITY_PK
  PRIMARY KEY
  (MUNICIPALITYID)
  USING INDEX &schema_name..E_MUNICIPALITY_PK
  ENABLE VALIDATE);


Prompt Table E_PROJECT;
CREATE TABLE &schema_name..E_PROJECT
(
  PROJECTID  NUMBER(9)                          NOT NULL,
  NAME       VARCHAR2(256 BYTE)                 NOT NULL,
  STARTDATE  DATE,
  ENDDATE    DATE,
  USERID     NUMBER(9),
  CREATEDAT  DATE,
  UPDATEDAT  DATE,
  STATEID    VARCHAR2(10 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE;


Prompt Index E_PROJECT_PK;
CREATE UNIQUE INDEX &schema_name..E_PROJECT_PK ON &schema_name..E_PROJECT
(PROJECTID)
LOGGING;

ALTER TABLE &schema_name..E_PROJECT ADD (
  CONSTRAINT E_PROJECT_PK
  PRIMARY KEY
  (PROJECTID)
  USING INDEX &schema_name..E_PROJECT_PK
  ENABLE VALIDATE);


Prompt Table E_STATES;
CREATE TABLE &schema_name..E_STATES
(
  STATEID  VARCHAR2(10 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE;

Prompt Index E_STATES_PK;
CREATE UNIQUE INDEX &schema_name..E_STATES_PK ON &schema_name..E_STATES
(STATEID)
LOGGING;

ALTER TABLE &schema_name..E_STATES ADD (
  CONSTRAINT E_STATES_PK
  PRIMARY KEY
  (STATEID)
  USING INDEX &schema_name..E_STATES_PK
  ENABLE VALIDATE);


Prompt Table E_TASK;
CREATE TABLE &schema_name..E_TASK
(
  TASKID     NUMBER(9),
  NAME       VARCHAR2(256 BYTE)                 NOT NULL,
  GLOSS      VARCHAR2(4000 BYTE),
  CREATEDAT  DATE                               NOT NULL,
  UPDATEDAT  DATE,
  STATEID    VARCHAR2(10 BYTE)                  NOT NULL,
  USERID     NUMBER(9)                          NOT NULL,
  PROJECTID  NUMBER(9)
)
LOGGING 
NOCOMPRESS 
NOCACHE;


Prompt Index E_TASK_PK;
CREATE UNIQUE INDEX &schema_name..E_TASK_PK ON &schema_name..E_TASK
(TASKID)
LOGGING;

ALTER TABLE &schema_name..E_TASK ADD (
  CONSTRAINT E_TASK_PK
  PRIMARY KEY
  (TASKID)
  USING INDEX &schema_name..E_TASK_PK
  ENABLE VALIDATE);


Prompt Table E_USER;
CREATE TABLE &schema_name..E_USER
(
  USERID          NUMBER(9),
  NAME            VARCHAR2(256 BYTE)            NOT NULL,
  LASTNAME        VARCHAR2(256 BYTE)            NOT NULL,
  ADDRESS         VARCHAR2(256 BYTE),
  PHONE           VARCHAR2(18 BYTE),
  COUNTRYID       NUMBER(9),
  MUNICIPALITYID  NUMBER(9),
  EMAIL           VARCHAR2(256 BYTE)            NOT NULL,
  CREATEDAT       DATE,
  UPDATEDAT       DATE,
  STATEID         VARCHAR2(10 BYTE)             NOT NULL,
  USERNAME        VARCHAR2(50 BYTE)             NOT NULL
)
LOGGING 
NOCOMPRESS 
NOCACHE;


Prompt Index E_USER_PK;
CREATE UNIQUE INDEX &schema_name..E_USER_PK ON &schema_name..E_USER
(USERID)
LOGGING;

ALTER TABLE &schema_name..E_USER ADD (
  CONSTRAINT E_USER_PK
  PRIMARY KEY
  (USERID)
  USING INDEX &schema_name..E_USER_PK
  ENABLE VALIDATE);


Prompt Sequence SECAUDITID;
CREATE SEQUENCE &schema_name..SECAUDITID
  START WITH 1
  MAXVALUE 9999999999999999999999999999
  MINVALUE 0
  NOCYCLE
  CACHE 20
  NOORDER
  NOKEEP
  NOSCALE
  GLOBAL;

Prompt Synonym E_AUDIT;
CREATE OR REPLACE PUBLIC SYNONYM E_AUDIT FOR &schema_name..E_AUDIT;


Prompt Synonym E_COUNTRY;
CREATE OR REPLACE PUBLIC SYNONYM E_COUNTRY FOR &schema_name..E_COUNTRY;


Prompt Synonym E_MUNICIPALITY;
CREATE OR REPLACE PUBLIC SYNONYM E_MUNICIPALITY FOR &schema_name..E_MUNICIPALITY;


Prompt Synonym E_PROJECT;
CREATE OR REPLACE PUBLIC SYNONYM E_PROJECT FOR &schema_name..E_PROJECT;


Prompt Synonym E_STATES;
CREATE OR REPLACE PUBLIC SYNONYM E_STATES FOR &schema_name..E_STATES;


Prompt Synonym E_TASK;
CREATE OR REPLACE PUBLIC SYNONYM E_TASK FOR &schema_name..E_TASK;


Prompt Synonym E_USER;
CREATE OR REPLACE PUBLIC SYNONYM E_USER FOR &schema_name..E_USER;


ALTER TABLE &schema_name..E_MUNICIPALITY ADD (
  CONSTRAINT MUNICIPALITY_COUNTRY_FK 
  FOREIGN KEY (COUNTRYID) 
  REFERENCES &schema_name..E_COUNTRY (COUNTRYID)
  ENABLE VALIDATE);

ALTER TABLE &schema_name..E_PROJECT ADD (
  CONSTRAINT PROJECT_USER_FK 
  FOREIGN KEY (USERID) 
  REFERENCES &schema_name..E_USER (USERID)
  ENABLE VALIDATE);

ALTER TABLE &schema_name..E_TASK ADD (
  CONSTRAINT TASK_PROJECT_FK 
  FOREIGN KEY (PROJECTID) 
  REFERENCES &schema_name..E_PROJECT (PROJECTID)
  ENABLE VALIDATE
,  CONSTRAINT TASK_USER_FK 
  FOREIGN KEY (USERID) 
  REFERENCES &schema_name..E_USER (USERID)
  ENABLE VALIDATE);

ALTER TABLE &schema_name..E_USER ADD (
  CONSTRAINT USER_COUNTRY_FK 
  FOREIGN KEY (COUNTRYID) 
  REFERENCES &schema_name..E_COUNTRY (COUNTRYID)
  ENABLE VALIDATE
,  CONSTRAINT USER_MUNICIPALITY_FK 
  FOREIGN KEY (MUNICIPALITYID) 
  REFERENCES &schema_name..E_MUNICIPALITY (MUNICIPALITYID)
  ENABLE VALIDATE);


Prompt Insertando Datos en las Tablas del Modelo

Prompt Insertando en E_COUNTRY
SET DEFINE OFF;
Insert into E_COUNTRY
   (COUNTRYID, NAME)
 Values
   (1, 'COLOMBIA');
Insert into E_COUNTRY
   (COUNTRYID, NAME)
 Values
   (2, 'MEXICO');
Insert into E_COUNTRY
   (COUNTRYID, NAME)
 Values
   (3, 'ARGENTINA');
COMMIT;

Prompt Insertando en E_MUNICIPALITY
SET DEFINE OFF;
Insert into E_MUNICIPALITY
   (MUNICIPALITYID, NAME, COUNTRYID)
 Values
   (1, 'BOGOTA DC', 1);
Insert into E_MUNICIPALITY
   (MUNICIPALITYID, NAME, COUNTRYID)
 Values
   (2, 'MEDELLIN', 1);
Insert into E_MUNICIPALITY
   (MUNICIPALITYID, NAME, COUNTRYID)
 Values
   (3, 'BARRANQUILLA', 1);
Insert into E_MUNICIPALITY
   (MUNICIPALITYID, NAME, COUNTRYID)
 Values
   (5, 'CALI', 1);
COMMIT;

Prompt Insertando en E_STATES
SET DEFINE OFF;
Insert into E_STATES
   (STATEID)
 Values
   ('CLOSE');
Insert into E_STATES
   (STATEID)
 Values
   ('DELETED');
Insert into E_STATES
   (STATEID)
 Values
   ('DISABLED');
Insert into E_STATES
   (STATEID)
 Values
   ('ENABLED');
Insert into E_STATES
   (STATEID)
 Values
   ('OPEN');
COMMIT;

Prompt Insertando en E_USER
SET DEFINE OFF;
Insert into E_USER
   (USERID, NAME, LASTNAME, ADDRESS, PHONE, 
    COUNTRYID, MUNICIPALITYID, EMAIL, CREATEDAT, UPDATEDAT, 
    STATEID, USERNAME)
 Values
   (384577153, 'LINA', 'TORO', 'CRA 45 NRO 35-52', '3184523639', 
    1, 2, 'lina.toro@email.com', SYSDATE, NULL, 
    'ENABLED', 'LINA.TORO');
Insert into E_USER
   (USERID, NAME, LASTNAME, ADDRESS, PHONE, 
    COUNTRYID, MUNICIPALITYID, EMAIL, CREATEDAT, UPDATEDAT, 
    STATEID, USERNAME)
 Values
   (39845214, 'JULIAN', 'CARDONA', 'CRA 41 NRO 30-54', '3464853632', 
    1, 2, 'julian.cardona@email.com', SYSDATE, NULL, 
    'ENABLED', 'JULIAN.CARDONA');
COMMIT;


Prompt Insertando en E_PROJECT
SET DEFINE OFF;
Insert into E_PROJECT
   (PROJECTID, NAME, STARTDATE, ENDDATE, USERID, 
    CREATEDAT, UPDATEDAT, STATEID)
 Values
   (1, 'Proyecto demo', SYSDATE, SYSDATE+30, 39845214, 
    SYSDATE, NULL, NULL);
COMMIT;

Prompt Insertando en E_TASK
SET DEFINE OFF;
Insert into E_TASK
   (TASKID, NAME, GLOSS, CREATEDAT, UPDATEDAT, 
    STATEID, USERID, PROJECTID)
 Values
   (1, 'TAREA 1', 'Especificacion de la tarea 1', SYSDATE, NULL, 
    'OPEN', 39845214, NULL);
COMMIT;

SET TIMING OFF
SPOOL OFF
Prompt Finaliza
