Prompt Table E_AUDIT;
CREATE TABLE &SCHEMA..E_AUDIT
(
  AUDITID        NUMBER(9),
  TABLENAME      VARCHAR2(100 BYTE),
  OBJECTEXECUTE  VARCHAR2(100 BYTE),
  OPERATION      VARCHAR2(10 BYTE),
  CREATEAT       DATE,
  UPDATEAT       DATE,
  MODULE         VARCHAR2(100 BYTE),
  VALUEOLD       VARCHAR2(4000 BYTE),
  VALUENEW       VARCHAR2(4000 BYTE),
  ATRIBUTE       VARCHAR2(100 BYTE),
  GLOSSA         VARCHAR2(4000 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE;


Prompt Index E_AUDITORIA_PK;
CREATE UNIQUE INDEX &SCHEMA..E_AUDITORIA_PK ON &SCHEMA..E_AUDIT
(AUDITID)
LOGGING;

ALTER TABLE &SCHEMA..E_AUDIT ADD (
  CONSTRAINT E_AUDITORIA_PK
  PRIMARY KEY
  (AUDITID)
  USING INDEX &SCHEMA..E_AUDITORIA_PK
  ENABLE VALIDATE);


Prompt Synonym E_AUDIT;
CREATE OR REPLACE PUBLIC SYNONYM E_AUDIT FOR &SCHEMA..E_AUDIT;


