Prompt Table E_COUNTRY;
CREATE TABLE &SCHEMA..E_COUNTRY
(
  COUNTRYID  NUMBER(9),
  NAME       VARCHAR2(256 BYTE)                 NOT NULL
)
LOGGING 
NOCOMPRESS 
NOCACHE;


Prompt Index E_COUNTRY_PK;
CREATE UNIQUE INDEX E_COUNTRY_PK ON &SCHEMA..E_COUNTRY
(COUNTRYID)
LOGGING;

ALTER TABLE &SCHEMA..E_COUNTRY ADD (
  CONSTRAINT E_COUNTRY_PK
  PRIMARY KEY
  (COUNTRYID)
  USING INDEX &SCHEMA..E_COUNTRY_PK
  ENABLE VALIDATE);


Prompt Synonym E_COUNTRY;
CREATE OR REPLACE PUBLIC SYNONYM E_COUNTRY FOR &SCHEMA..E_COUNTRY;

