Prompt Table E_PROJECT;
CREATE TABLE &SCHEMA..E_PROJECT
(
  PROJECTID  NUMBER(9)                          NOT NULL,
  NAME       VARCHAR2(256 BYTE)                 NOT NULL,
  STARTDATE  DATE,
  ENDDATE    DATE,
  USERID     NUMBER(9),
  CREATEDAT  DATE,
  UPDATEDAT  DATE,
  STATEID    VARCHAR2(10 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE;


Prompt Index E_PROJECT_PK;
CREATE UNIQUE INDEX &SCHEMA..E_PROJECT_PK ON &SCHEMA..E_PROJECT
(PROJECTID)
LOGGING;

ALTER TABLE &SCHEMA..E_PROJECT ADD (
  CONSTRAINT E_PROJECT_PK
  PRIMARY KEY
  (PROJECTID)
  USING INDEX &SCHEMA..E_PROJECT_PK
  ENABLE VALIDATE);


Prompt Synonym E_PROJECT;
CREATE OR REPLACE PUBLIC SYNONYM E_PROJECT FOR &SCHEMA..E_PROJECT;


ALTER TABLE &SCHEMA..E_PROJECT ADD (
  CONSTRAINT PROJECT_USER_FK 
  FOREIGN KEY (USERID) 
  REFERENCES &SCHEMA..E_USER (USERID)
  ENABLE VALIDATE);