Prompt Table E_STATES;
CREATE TABLE &SCHEMA..E_STATES
(
  STATEID  VARCHAR2(10 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE;


Prompt Index E_STATES_PK;
CREATE UNIQUE INDEX &SCHEMA..E_STATES_PK ON &SCHEMA..E_STATES
(STATEID)
LOGGING;

ALTER TABLE &SCHEMA..E_STATES ADD (
  CONSTRAINT E_STATES_PK
  PRIMARY KEY
  (STATEID)
  USING INDEX &SCHEMA..E_STATES_PK
  ENABLE VALIDATE);


Prompt Synonym E_STATES;
CREATE OR REPLACE PUBLIC SYNONYM E_STATES FOR &SCHEMA..E_STATES;


SET DEFINE OFF;
Insert into &SCHEMA..E_STATES
   (STATEID)
 Values
   ('CLOSE');
Insert into &SCHEMA..E_STATES
   (STATEID)
 Values
   ('DELETED');
Insert into &SCHEMA..E_STATES
   (STATEID)
 Values
   ('DISABLED');
Insert into &SCHEMA..E_STATES
   (STATEID)
 Values
   ('ENABLED');
Insert into &SCHEMA..E_STATES
   (STATEID)
 Values
   ('OPEN');
COMMIT;
