Prompt Table E_TASK;
CREATE TABLE &SCHEMA..E_TASK
(
  TASKID     NUMBER(9),
  NAME       VARCHAR2(256 BYTE)                 NOT NULL,
  GLOSS      VARCHAR2(4000 BYTE),
  CREATEDAT  DATE                               NOT NULL,
  UPDATEDAT  DATE,
  STATEID    VARCHAR2(10 BYTE)                  NOT NULL,
  USERID     NUMBER(9)                          NOT NULL,
  PROJECTID  NUMBER(9)
)
LOGGING 
NOCOMPRESS 
NOCACHE;


Prompt Index E_TASK_PK;
CREATE UNIQUE INDEX &SCHEMA..E_TASK_PK ON &SCHEMA..E_TASK
(TASKID)
LOGGING;

ALTER TABLE &SCHEMA..E_TASK ADD (
  CONSTRAINT E_TASK_PK
  PRIMARY KEY
  (TASKID)
  USING INDEX &SCHEMA..E_TASK_PK
  ENABLE VALIDATE);


Prompt Sequence SECAUDITID;
CREATE SEQUENCE &SCHEMA..SECAUDITID
  START WITH 1
  MAXVALUE 9999999999999999999999999999
  MINVALUE 0
  NOCYCLE
  CACHE 20
  NOORDER
  NOKEEP
  NOSCALE
  GLOBAL;

Prompt Synonym E_TASK;
CREATE OR REPLACE PUBLIC SYNONYM E_TASK FOR &SCHEMA..E_TASK;

ALTER TABLE &SCHEMA..E_TASK ADD (
  CONSTRAINT TASK_PROJECT_FK 
  FOREIGN KEY (PROJECTID) 
  REFERENCES &SCHEMA..E_PROJECT (PROJECTID)
  ENABLE VALIDATE
,  CONSTRAINT TASK_USER_FK 
  FOREIGN KEY (USERID) 
  REFERENCES &SCHEMA..E_USER (USERID)
  ENABLE VALIDATE);
