Prompt Table E_USER;
CREATE TABLE &SCHEMA..E_USER
(
  USERID          NUMBER(9),
  NAME            VARCHAR2(256 BYTE)            NOT NULL,
  LASTNAME        VARCHAR2(256 BYTE)            NOT NULL,
  ADDRESS         VARCHAR2(256 BYTE),
  PHONE           VARCHAR2(18 BYTE),
  COUNTRYID       NUMBER(9),
  MUNICIPALITYID  NUMBER(9),
  EMAIL           VARCHAR2(256 BYTE)            NOT NULL,
  CREATEDAT       DATE,
  UPDATEDAT       DATE,
  STATEID         VARCHAR2(10 BYTE)             NOT NULL,
  USERNAME        VARCHAR2(50 BYTE)             NOT NULL
)
LOGGING 
NOCOMPRESS 
NOCACHE;


Prompt Index E_USER_PK;
CREATE UNIQUE INDEX &SCHEMA..E_USER_PK ON &SCHEMA..E_USER
(USERID)
LOGGING;

ALTER TABLE &SCHEMA..E_USER ADD (
  CONSTRAINT E_USER_PK
  PRIMARY KEY
  (USERID)
  USING INDEX &SCHEMA..E_USER_PK
  ENABLE VALIDATE);


Prompt Synonym E_USER;
CREATE OR REPLACE PUBLIC SYNONYM E_USER FOR &SCHEMA..E_USER;


ALTER TABLE &SCHEMA..E_USER ADD (
  CONSTRAINT USER_COUNTRY_FK 
  FOREIGN KEY (COUNTRYID) 
  REFERENCES &SCHEMA..E_COUNTRY (COUNTRYID)
  ENABLE VALIDATE
,  CONSTRAINT USER_MUNICIPALITY_FK 
  FOREIGN KEY (MUNICIPALITYID) 
  REFERENCES &SCHEMA..E_MUNICIPALITY (MUNICIPALITYID)
  ENABLE VALIDATE);
